---
title: Temps d'Images
timezone: UTC
collections:
  events:
    title: Events
    output: true
  events_eng:
    title: Events Eng
    output: true
  film:
    title: Film
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: duplacena@duplacena.com
description: Debruçando-se sobre a relação entre as artes cénicas e a imagem em movimento,
  o TEMPS D’IMAGES é um festival multi-disciplinar que apresenta peças de teatro,
  performances, espectáculos, exposições e filmes em vários locais de Lisboa.
url: https://tempsdimages-portugal.com
permalink: pretty
plugins:
- jekyll-feed
sass:
  sass_dir: _sass
