backend:
  name: git-gateway
  branch: main
  
media_folder: "assets/img" # Branch to update (optional; defaults to master)

collections:
  - name: "event" # Used in routes, e.g., /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "_events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Imagem", name: "image", widget: "image", media_library: {allow_multiple: false}}
      - {label: "Crédito Imagem", name: "credit_image", widget: "string", required: false}
      - {label: "Link Bilhetes", name: "link_bilhetes", widget: "string", required: false, hint: "Adicionar o link aqui. Caso a entrada seja livre, escrever apenas: entrada livre. Para 'bilhetes em breve': deixar em branco."}
      - {label: "Nome do Espétaculo", name: "title", widget: "string", required: false}
      - {label: "Nome Artista", name: "artist", widget: "string", required: false}
      - {label: "Data de Inicio", name: "start_date", widget: "datetime", dateFormat: "DD/MM/YYYY", timeFormat: "", utc: false, required: false, hint: "(para ordenar os projetos)"}
      - {label: "Dias", name: "dias", widget: "list", default: [], required: false, hint: "Adicionar os dias em que o evento ocorre. Dia/Mês como elementos separados. ex: 12-5, 13-5, 14-5. Para que se possa filtrar por dia."}
      - {label: "Data(s) e hora", name: "dates", widget: "string", required: false, hint: "Exemplo formato: 14-16 maio 2022, 19h"}
      - {label: "Outra data", name: "other_date", widget: "string", required: false, hint: "(se houver horário alternativo)"}
      - {label: "Local", name: "venue", widget: "string", required: false}
      - {label: "Classificação", name: "age", widget: "string", required: false}
      - {label: "Duração", name: "duracao", widget: "string", required: false}
      - {label: "Estreia", name: "estreia", widget: "string", required: false}
      - {label: "Sinopse", name: "synopsis", widget: "html", required: false}
      - {label: "Ficha Técnica", name: "tech", widget: "html", required: false}
      - {label: "Biografias", name: "bios", widget: "list", fields: [
          {label: "Nome Artista", name: "artist_bio", widget: "string", required: false},
          {label: "Biografia", name: "bio", widget: "html", required: false}
        ], required: false}
      - {label: "Parceiros", name: "parceiros", widget: "list", field: {label: "Parceiro", name: "partner", widget: "image"}, required: false}


